# Generated by Django 5.0.4 on 2024-04-15 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_process", "in_process"),
                            ("processed", "processed"),
                        ],
                        default="in_process",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "file",
            },
        ),
        migrations.CreateModel(
            name="Coordinate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("postal_code", models.CharField(max_length=10, null=True)),
                (
                    "process_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processed", "processed"),
                            ("not_found", "not_found"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coordinates_manager.file",
                    ),
                ),
            ],
            options={
                "db_table": "coordinate",
            },
        ),
    ]
